cluster-config: "cluster_config.yaml"
config: "samples=atlas/samples.tsv"
configfile: "conf/config.yml"
use-conda: true
jobs: 100
conda-frontend: mamba
reason: true
slurm: true
cores: 99 # how many jobs you want to submit to your cluster queue
local-cores: 1
rerun-incomplete: true  # recomended for cluster submissions
keep-going: true
reason: true
printshellcmds: true
default-resources: "slurm_account=naiss2023-5-326"
